name: Query Builder CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: borales/actions-yarn@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn ci
      - run: yarn test
